CREATE TABLE `links`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `link` VARCHAR(255) NOT NULL,
    `code` VARCHAR(255) NOT NULL,
    `user` VARCHAR(255) DEFAULT NULL,
    `added` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (`code`)
);

CREATE TABLE `visit`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `code` VARCHAR(255) NOT NULL,
    `user_agent` VARCHAR(255) NOT NULL,
    `ip` VARCHAR(255) NOT NULL,
    `time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT `add_visit` FOREIGN KEY (`code`) REFERENCES `links`(`code`) ON DELETE CASCADE
);

