CREATE DATABASE `main`;

USE `main`;

CREATE TABLE `links`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `orig_url` VARCHAR(255) NOT NULL,
    `short_url` VARCHAR(255) NOT NULL,
    `stats_url` VARCHAR(255) NOT NULL,
    `user` VARCHAR(255) NULL,
    `added` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `visit`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `link` BIGINT NOT NULL,
    `user_agent` VARCHAR(255) NOT NULL,
    `ip` VARCHAR(255) NOT NULL,
    `time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

